    String sHeading1;
    String sConfiguration;
    String sSettings;
    String sLanguage;
    String sDeselected;
    String sEnselected;   
    String sFillprocess;
    String sWaitforfillbottle;
    String sPurgecycles;
    String sPurgein;
    String sPurgeinpostdelay;
    String sPurgeoutpostdelay;
    String sPurgeout;
    String sBottles;
    String sBottletolerance;
    String sScaletolerance;
    String sBottletypes;
    String sBottle1vol;
    String sBottle1weight;
    String sBottle2vol;
    String sBottle2weight;
    String sBottle3vol;
    String sBottle3weight;
    String sCalibration;
    String sWaitforcalibrationbottle;
    String sCIPprocess;
    String sWaitforcipbottle;
    String sCleancycles;
    String sCleanpurgeout;
    String sCleanschmockeout;
    String sScalecalibration;
    String sInstructions;
    String sReferenceweight;
    String sSave;
    String sWeight;
    String sManuop;
    String sMainmenu;
    String sEmergencystop;
    String sManual;
    String sSubmit;
    String sTestscale;
    String sBottleinstructions;

void set_language(){
  if (language==1){
     sDeselected="selected";
     sEnselected="";   
     sHeading1= "iTap Flaschenf&uuml;ller";
     sConfiguration= "Konfigurationsparameter";
     sSettings= "Generelle Einstellungen";
     sLanguage= "Sprache";
     sFillprocess= "F&uuml;llprozess";
     sWaitforfillbottle= "Wartezyklen bis zum &Uuml;berspringen des F&uuml;llprozesses";
     sPurgecycles="CO2 Flutungszyklen";
     sPurgein="CO2 Flutungszeit [ms]";
     sPurgeinpostdelay="Flutungspause [ms]";
     sPurgeoutpostdelay="Entl&uuml;ftungspause [ms]";
     sPurgeout="CO2 Entl&uuml;ftungszeit [ms]";
     sBottles= "Flaschentypen";
     sScaletolerance= "Toleranz bei Flaschenerbruchkennung (Pl&ouml;tzlicher Gewichtsverlust) -[g]";
     sBottletolerance= "Toleranz bei Flaschenerkennung [%]";
     sBottletypes= "Anzahl Flaschentypen in Gebrauch";
     sBottle1vol= "Flaschenvolumen 1 [ml]";
     sBottle1weight= "Flaschengewicht 1 [g]";
     sBottle2vol= "Flaschenvolumen 2 [ml]";
     sBottle2weight= "Flaschengewicht 2 [g]";
     sBottle3vol= "Flaschenvolumen 3 [ml]";
     sBottle3weight= "Flaschengewicht 3 [g]";
     sCalibration= "Kalibrierprozess";
     sWaitforcalibrationbottle= "Wartezyklen bis zum &Uuml;berspringen des Kalibrierungsprozesses";
     sCIPprocess= "Reinigungsprozess";
     sWaitforcipbottle= "Wartezyklen bis zum &Uuml;berspringen des Reinigungsprozesses";
     sCleancycles= "Reinigungszyklen";
     sCleanpurgeout= "Sp&uuml;ldauer Schnellablassventil [ms]";
     sCleanschmockeout= "Sp&uuml;ldauer Feinablassventil [ms]";
     sScalecalibration="Kalibrierung der Waage";
     sInstructions="Gef&uuml;llte Flasche mit bekanntem Gewicht einh&auml;ngen, warten bis rote LED erloschen, dann 'Speichern' dr&uuml;cken.";
     sReferenceweight="Bekanntes Gewicht [g]";
     sWeight = "Gewicht";
     sSave = "Speichern";
     sManuop= "Manuelle Bedienung";
     sMainmenu="Hauptmen&uuml;";
     sEmergencystop="Notaus";
     sManual="Handbetrieb";
     sSubmit="&Uuml;bernehmen";
     sTestscale="Waagentest";
     sBottleinstructions="Flaschenkalibrierung: leere oder gef&uuml;llte Flasche einh&auml;ngen und gemessenen Wert der Wage mit entsprechendem Knopfdruck &uuml;bernehmen.";
 }  else {
     sHeading1= "iTap Bottlefiller";
     sConfiguration= "Configuration Parameters";
     sSettings= "General settings";
     sLanguage= "Language";
     sDeselected="";
     sEnselected="selected";   
     sFillprocess= "Fillprocess";
     sWaitforfillbottle= "Waiting cycles for skipping the fill process";
     sPurgecycles="CO2 flood cycles";
     sPurgein="CO2 flood time [ms]";
     sPurgeinpostdelay="Flood delay [ms]";
     sPurgeoutpostdelay="Vent delay[ms]";
     sPurgeout="CO2 vent time [ms]";
     sBottletolerance= "Bottle recognition tolerance [%]";
     sScaletolerance= "Toleranz bei Flaschenerbruchkennung (Plötzlicher Gewichtsverlust)";
     sBottles= "Bottletypes";
     sBottletypes= "Number of bottle types in use";
     sBottle1vol= "Bottle volume 1 [ml]";
     sBottle1weight= "Bottle weight 1 [g]";
     sBottle2vol= "Bottle volume 2 [ml]";
     sBottle2weight= "Bottle weight 2 [g]";
     sBottle3vol= "Bottle volume 3 [ml]";
     sBottle3weight= "Bottle weight3 [g]";
     sCalibration= "Calibration prozess";
     sWaitforcalibrationbottle= "Waiting cycles for skipping the calibration process";
     sCIPprocess= "CIP process";
     sWaitforcipbottle= "Waiting cycles for skipping the cip process";
     sCleancycles= "Cleaning cycles";
     sCleanpurgeout= "Flood duration fast vent [ms]";
     sCleanschmockeout= "Flood duration slow vent [ms]";
     sScalecalibration="Scale Calibration"; 
     sInstructions="Hang up filled bottle with known weight, wait until red LED is off and press 'Enter'";
     sReferenceweight="Known weight [g]";
     sWeight="Weight";
     sSave = "Save";
     sManuop= "Manual operation";
     sMainmenu="Main menu";
     sEmergencystop="Emergency stop";
     sManual="Manual mode";
     sSubmit="Submit";
     sTestscale="Test scale";
     sBottleinstructions="Bottle Calibration: hang up empty or filled bottle and save measured value by pressing related 'Submit' button.";
   }
}